# Generated by Django 2.0.2 on 2018-02-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(default='89', max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
