# Generated by Django 2.0.2 on 2018-02-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='zip_code',
            field=models.CharField(default='89169', max_length=5),
        ),
    ]
