# Generated by Django 2.0.2 on 2018-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20180211_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Las Vegas', max_length=64),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='state',
            field=models.CharField(default='NV', max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
