# Generated by Django 2.0.2 on 2018-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20180211_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=400)),
                ('info', models.TextField(blank=True)),
                ('image_source', models.CharField(max_length=120)),
            ],
        ),
    ]
