# Generated by Django 2.0.2 on 2018-05-17 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('wedding', '0005_funstuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('relation', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=120)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.FunStuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Person')),
            ],
        ),
    ]
