# Generated by Django 2.0.2 on 2018-06-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20180518_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funstuff',
            options={'verbose_name_plural': 'Fun Stuff'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
