# Generated by Django 2.0.2 on 2018-06-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20180604_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locals'},
        ),
    ]
