# Generated by Django 2.0.2 on 2018-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_auto_20180604_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='number',
            field=models.CharField(default='SQBKT5W3jaW93cfJkGOMQJd5fFr9Y1w90', max_length=36),
        ),
    ]
