# Generated by Django 2.0.2 on 2018-06-22 01:48

from django.db import migrations, models
import wedding.models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_local_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='number',
            field=models.CharField(default=wedding.models.Local.getCode, max_length=36, unique=True),
        ),
    ]
