# Generated by Django 2.0.2 on 2018-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_auto_20180622_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funstuff',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Drinks', 'Drinks'), ('Outdoors', 'Outdoors')], default='Entertainment', max_length=13),
        ),
    ]
