# Generated by Django 2.0.2 on 2018-08-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_auto_20180819_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=120)),
                ('when', models.CharField(max_length=120)),
                ('where', models.CharField(max_length=120)),
                ('where_link', models.CharField(max_length=120)),
                ('who', models.CharField(max_length=120)),
                ('attire', models.CharField(max_length=120)),
                ('transportation', models.TextField(blank=True)),
                ('other', models.TextField(blank=True)),
            ],
        ),
    ]
