# Generated by Django 2.0.2 on 2018-08-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
