# Generated by Django 2.0.2 on 2018-08-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0016_auto_20180819_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
