# Generated by Django 2.0.2 on 2018-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_event_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
